name: Build and push images

on:
  workflow_dispatch:
    inputs:
      buildType:
        description: Decide on what to build
        required: true
        type: choice
        options:
          - build_push
          - build_only
      tag:
        description: Tag to build the image with
        required: true
        type: string
        default: latest
  push:
    branches:
      - main

jobs:
  build_and_push:
    name: Build and push dynamic and static harvest source images
    runs-on: ubuntu-latest
    permissions:
      packages: write
    env:
      tag: ${{ inputs.tag || 'latest' }}
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.gitRef }}
      - name: Build dynamic
        if: ${{ inputs.buildType == 'build_only' }}
        uses: docker/build-push-action@v6
        with:
          context: ./dynamic
          push: false
          tags: ghcr.io/alphagov/dynamic-ckan-harvest-source:${{ tag }}
      - name: Build static
        if: ${{ inputs.buildType == 'build_only' }}
        uses: docker/build-push-action@v6
        with:
          context: ./static
          push: false
          tags: ghcr.io/alphagov/static-ckan-harvest-source:${{ tag }}
      - name: Build and push dynamic
        if: ${{ inputs.buildType == 'build_push' || github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v6
        with:
          context: ./dynamic
          push: true
          tags: ghcr.io/alphagov/dynamic-ckan-harvest-source:${{ tag }}
      - name: Build and push static
        if: ${{ inputs.buildType == 'build_push' || github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v6
        with:
          context: ./static
          push: true
          tags: ghcr.io/alphagov/static-ckan-harvest-source:${{ tag }}
